name: gluco_guide
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  dots_indicator: ^3.0.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^9.0.0
  pinput: ^3.0.1
  expansion_tile_card: ^3.0.0
  flutter_rating_stars: ^1.0.3+4
  freezed_annotation: ^2.4.1
  dio: ^5.3.4
  get_it: ^7.6.4
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sign_in_with_apple: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.0.2
  badges: ^3.0.2
  easy_localization: ^3.0.1
  google_sign_in: ^6.1.6
  lottie: ^2.7.0
  gap: ^3.0.1
  flutter_spinkit: ^5.2.0
  faker: ^2.1.0
  calendar_date_picker2: ^0.5.2
  adaptive_dialog: ^2.0.0
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  animated_bottom_navigation_bar: ^1.3.3
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  riverpod_lint: ^2.0.3

flutter_gen:
  output: lib/gen/
  line_length: 80


  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
    video_player: true


  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
    class_name: ResAssets
  fonts:
    enabled: true

  colors:
    enabled: true
    class_name: AssetsColors
    inputs:
      - assets/colors/colors.xml
flutter:

  uses-material-design: true
  assets:
    - assets/env/
    - assets/env/env_prod.env
    - assets/env/env_dev.env
    - assets/env/env_base.env
    - assets/images/
    - assets/translations/en.json
    - assets/icons/
    - assets/fonts/Lato/
    - assets/images/workout/
    - assets/gif/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Medium.ttf




