// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xrOBA9WwHdSIJcURb1nsgAQDiPhPT_I',
    appId: '1:960945048289:web:010276441c463f45a085a0',
    messagingSenderId: '960945048289',
    projectId: 'gluco-guide-8242a',
    authDomain: 'gluco-guide-8242a.firebaseapp.com',
    storageBucket: 'gluco-guide-8242a.appspot.com',
    measurementId: 'G-XHVE79B4S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0qXIrXlCqI12MA3i8zQipteGknqpCd8',
    appId: '1:960945048289:android:9d72d9331fcff953a085a0',
    messagingSenderId: '960945048289',
    projectId: 'gluco-guide-8242a',
    storageBucket: 'gluco-guide-8242a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxtLG9sv9zVr5QZYIfZdUT0RGoD4MJ1U',
    appId: '1:960945048289:ios:7b22bdb180e99c04a085a0',
    messagingSenderId: '960945048289',
    projectId: 'gluco-guide-8242a',
    storageBucket: 'gluco-guide-8242a.appspot.com',
    iosBundleId: 'com.example.glucoGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxtLG9sv9zVr5QZYIfZdUT0RGoD4MJ1U',
    appId: '1:960945048289:ios:7b22bdb180e99c04a085a0',
    messagingSenderId: '960945048289',
    projectId: 'gluco-guide-8242a',
    storageBucket: 'gluco-guide-8242a.appspot.com',
    iosBundleId: 'com.example.glucoGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-xrOBA9WwHdSIJcURb1nsgAQDiPhPT_I',
    appId: '1:960945048289:web:75d863763cc15e2da085a0',
    messagingSenderId: '960945048289',
    projectId: 'gluco-guide-8242a',
    authDomain: 'gluco-guide-8242a.firebaseapp.com',
    storageBucket: 'gluco-guide-8242a.appspot.com',
    measurementId: 'G-M4LGNC49LE',
  );
}
